### ISSUE TITLE
Проблема запуска ggml версии

### ISSUE THREAD

**Issue by Samoed** [IlyaGusev/rulm#27]
Привет. Я пытался запустить `IlyaGusev/saiga2_7b_ggml`:
```bash
python interact_llamacpp.py ggml-model-q4_1.bin
```
 но получал ошибку
```
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from ggml-model-q4_1.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/home/samoed/Downloads/interact_llamacpp.py", line 73, in <module>
    fire.Fire(interact)
  File "/home/samoed/.pyenv/versions/3.10.4/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/samoed/.pyenv/versions/3.10.4/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/samoed/.pyenv/versions/3.10.4/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/samoed/Downloads/interact_llamacpp.py", line 41, in interact
    model = Llama(
  File "/home/samoed/.pyenv/versions/3.10.4/lib/python3.10/site-packages/llama_cpp/llama.py", line 323, in __init__
    assert self.model is not None
AssertionError
```
Пробывал даунгрейдить` llama-cpp-python==0.1.49`, но не помогло. Кто-то знает как решить это?

**Comment by IlyaGusev** [comment]
Так а модель-то скачана? Какая md5sum?

**Comment by IlyaGusev** [comment]
Впрочем воспроизвёл, на 0.1.65 вполне работает (между ggml v1 и gguf).
